version: '3.9'
services:
  qdrant_primary:
    image: "qdrant/qdrant:v0.8.0"
    ports:
      - "6333:6333"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
    command: ["./qdrant", "--uri", "http://qdrant_primary:6335"]
  qdrant_secondary:
    image: "qdrant/qdrant:v0.8.0"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
    command: ["./qdrant", "--bootstrap", "http://qdrant_primary:6335"]